spring:
  datasource:
    sql:
      url: jdbc:mysql://localhost:3306/nusa?createDatabaseIfNotExist=true
      username: root
      password: 03092002
    vector:
      url: jdbc:postgresql://localhost:5432/nusa-vector
      username: postgres
      password: 03092002
  jpa:
    show-sql: true
  file:
    upload:
      public: uploads/public
      private: uploads/private
ngrok:
  enabled: true
  authToken: ${NGROK_AUTH_TOKEN}