spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nusa?createDatabaseIfNotExist=true
    username: root
    password: 03092002
  jpa:
    show-sql: true
  file:
    upload:
      public: uploads/public
      private: uploads/private
ngrok:
  enabled: true
  authToken: ${NGROK_AUTH_TOKEN}