spring:
  application:
    name: Nusa360
  datasource:
    url: jdbc:mysql://localhost:3306/nusa?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 200 # 86400 # 1 day
    refreshTokenExpiration: 604800 # 7 days
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}