spring:
  application:
    name: Nusa360
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 86400 # 1 day
    refreshTokenExpiration: 604800 # 7 days
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
  profiles:
    active: dev
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080
  address: 0.0.0.0