spring:
  application:
    name: Nusa360
  datasource:
    url: jdbc:mysql://localhost:3306/nusa?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 86400 # 1 day
    refreshTokenExpiration: 604800 # 7 days
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
  file:
    upload:
      public: uploads/public # for prod use /var/www/myapp/uploads/public
      private: uploads/private # for prod use /var/www/myapp/uploads/private
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true